apiVersion: "xbank/v1beta1"
kind: "Gateway"
metadata:
  name: "repo2"
  version: "v1"
  minorVersion: "1.4"
  teamName: "A-Team"
spec:
  muhtar: "1.6.6"
  encumen: "1.2.3"
  contextPath: "/repo2-path"
  operations:
  - name: "getAlisgidisCustomerData"
    description: "getAlisgidisCustomerData"
    httpVerb: "POST"
    route: "/get-alisgidis-customer-data"
    target:
      httpVerb: "POST"
      host: "core-nonprelive"
      timeoutInSeconds: 120
      transformationHandledExceptionCodes:
      - "300"
      - "500"
      - 400
      route:
        type: "header"
        value: "RBF_GET_ALISGIDIS_CUSTOMER_DATA"
    transformation:
      request:
        filepath: "/repo2-path/getAlisgidisCustomerData/transformation/request.mjs"
        type: "middleware"
        timeoutInMilliSeconds: 4000
      response:
        filepath: "/repo2-path/getAlisgidisCustomerData/transformation/response.mjs"
        type: "middleware"
        timeoutInMilliSeconds: 4000
    validation:
      request:
        filepath: "/repo2-path/getAlisgidisCustomerData/validation/request.mjs"
      response:
        filepath: "/repo2-path/getAlisgidisCustomerData/validation/response.mjs"
    authorization:
      enabled: true
  transformationRepo:
    url: "https://github.com/zaferbozkurtsavana/apigw-repo2"
    tag: "v1.0.0"
